# Generated by Django 5.0.14 on 2026-01-27 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("1", "Factura Electrónica"),
                            ("2", "Factura Electrónica de Exportación"),
                            ("3", "Factura Electrónica de Importación"),
                            ("4", "Autofactura Electrónica"),
                            ("5", "Nota de Crédito Electrónica"),
                            ("6", "Nota de Débito Electrónica"),
                            ("7", "Nota de Remisión Electrónica"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("cdc", models.CharField(blank=True, max_length=44, unique=True)),
                ("timbrado", models.CharField(max_length=8)),
                ("receptor_ruc", models.CharField(blank=True, max_length=12)),
                ("receptor_nombre", models.CharField(max_length=255)),
                ("receptor_direccion", models.TextField(blank=True)),
                ("receptor_email", models.EmailField(blank=True, max_length=254)),
                ("fecha_emision", models.DateTimeField()),
                ("moneda", models.CharField(default="PYG", max_length=3)),
                (
                    "tipo_cambio",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                (
                    "subtotal_gravado_10",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "subtotal_gravado_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "subtotal_exento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_iva_10",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_iva_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente de envío"),
                            ("sent", "Enviado a SIFEN"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Anulado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sifen_response_code", models.CharField(blank=True, max_length=10)),
                ("sifen_response_message", models.TextField(blank=True)),
                ("sifen_batch_id", models.CharField(blank=True, max_length=50)),
                ("xml_signed", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="companies.establishmentpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
                "unique_together": {
                    ("company", "establishment", "document_type", "numero")
                },
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("descripcion", models.CharField(max_length=500)),
                ("unidad_medida", models.CharField(default="UNI", max_length=10)),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tasa_iva",
                    models.IntegerField(
                        choices=[(10, "10%"), (5, "5%"), (0, "Exento")], default=10
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Factura",
                "verbose_name_plural": "Ítems de Factura",
                "ordering": ["id"],
            },
        ),
    ]
