# Generated by Django 5.0.14 on 2026-01-27 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="RUC con dígito verificador (ej: 80012345-6)",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="RUC debe tener formato: 12345678-9",
                                regex="^\\d{1,8}-\\d$",
                            )
                        ],
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("nombre_fantasia", models.CharField(blank=True, max_length=255)),
                ("actividad_economica", models.CharField(max_length=10)),
                ("departamento", models.CharField(max_length=50)),
                ("distrito", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("timbrado", models.CharField(blank=True, max_length=8)),
                ("fecha_inicio_timbrado", models.DateField(blank=True, null=True)),
                ("fecha_fin_timbrado", models.DateField(blank=True, null=True)),
                ("certificado_path", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="EstablishmentPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_establecimiento", models.CharField(max_length=3)),
                ("codigo_punto", models.CharField(max_length=3)),
                ("descripcion", models.CharField(max_length=255)),
                ("direccion", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establishments",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Establecimiento",
                "verbose_name_plural": "Establecimientos",
                "ordering": ["codigo_establecimiento", "codigo_punto"],
                "unique_together": {
                    ("company", "codigo_establecimiento", "codigo_punto")
                },
            },
        ),
    ]
