# Generated by Django 5.0.14 on 2026-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SifenLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("send", "Envío DE"),
                            ("batch", "Envío Lote"),
                            ("query", "Consulta"),
                            ("cancel", "Anulación"),
                            ("event", "Evento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cdc", models.CharField(blank=True, db_index=True, max_length=44)),
                ("batch_id", models.CharField(blank=True, max_length=50)),
                ("request_xml", models.TextField(blank=True)),
                ("response_xml", models.TextField(blank=True)),
                ("response_code", models.CharField(max_length=10)),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name": "Log SIFEN",
                "verbose_name_plural": "Logs SIFEN",
                "ordering": ["-created_at"],
            },
        ),
    ]
